server:
  port: 8081

spring:
  application:
    name: msvc-user
  datasource:
    url: jdbc:mysql://localhost:3306/foodquart_user
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

security:
  jwt:
    secret: unaClaveSuperSecretaYSeguraDe32Caracteres!
    expiration: 3600000

appDescription: "Microservice user"
appVersion: "1.0.0"
